---

- name: Install PostgreSQL and prerequisites
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - postgresql
      - postgresql-contrib
      - python-psycopg2
      - postgresql-common
      - libpq-dev

- name: Copy PostgreSQL authentication configuration
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/10/main/pg_hba.conf
  notify: Restart PostgreSQL

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started

- name: Enable PostgreSQL
  service:
    name: postgresql
    enabled: yes

- name: Create {{ db_name }} database
  postgresql_db:
    login_user: postgres
    name: "{{ db_user }}"
    state: present

- name: Create {{ db_name }} database user
  postgresql_user:
    login_user: postgres
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    db: "{{ db_name }}"
    priv: ALL
    state: present
